export const menu = [
  {"nameEng":"Spring Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Onion Cake", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Deep Fried Goyza", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tempura Tofu", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Pork Katsu", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Chicken Katsu", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Chicken Karaage", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tempura Squid", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tempura Scollop", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Chicken Wings", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Golden Bun", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appetizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Carb Salad", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Salad", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Sweed Salad", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Salad", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Edamame Bean", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Salad", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Baccon Salad", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Salad", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Takoyaki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Appertizer", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tuna Maki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Maki Roll", "pcs" : 6,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Salmon Maki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Maki Roll", "pcs" : 6,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Avocado Maki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Maki Roll", "pcs" : 6,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Kappa Maki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Maki Roll", "pcs" : 6,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Mongo Maki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Maki Roll", "pcs" : 6,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Crab Maki", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Maki Roll", "pcs" : 6,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Spicy Salmon Cone", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Cone", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Spicy Tuna Cone", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Cone", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"A/C Cone", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Cone", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Kappa Cone", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Cone", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Mango Cone", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Cone", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Crab Cone", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Cone", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Red Tuna", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tako", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Hamachi", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Scollop", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Alborca Tuna", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Salmon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Thai (Snapper)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Mackerel", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Ebi (steamed Shrimp)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Crab Stick Sushi", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tamogo (Japanese Egg)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Surf Clam", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Nigiri Sushi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Red Tuna (max. 2pcs)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tako (max. 2pcs)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Hamachi (max. 2pcs)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Scollop (max. 2pcs)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":2, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Thai (Snapper)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Ebi (steamed Shrimp)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Crab Stick Sushi", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Tamogo (Japanese Egg)", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Surf Clam", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sashimi", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Golden Dragon Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Green Dragon Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Black Dragon Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Crush Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"BC Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Yam Tempura Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Mongo Crispy Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Salmon Avocado Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Rainbow Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Pilly Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"California Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Paynmit Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Spicy Tuna Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Spicy Salmon Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Spicy Crab Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"AC Roll", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Sushi Roll", "pcs" : 4,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Beef with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Chicken with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Pork with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Salmon with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Shrimp with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Seafood with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Beef with Yaki Undon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Chicken with Yaki Undon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Pork with Yaki Undon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Salmon with Fried Rice", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Shrimp with Yaki Undon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Seafood with Yaki Undon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Beef with Fried Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Chicken with Fried Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Pork with Fried Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Salmon with Fried Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Shrimp with Fried Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Terriyaki Seafood with Fried Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Teppanyaki", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Ramen", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Soup Noodle", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Udon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Soup Noodle", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Shrimp ", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Tempura", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Salmon", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Tempura", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Yam", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Tempura", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Pumpkin", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Tempura", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Brocolli", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Tempura", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  {"nameEng":"Eggplant", "nameChi" : "", "price" : 0, "categoryId" : "", "categoryName" : "Tempura", "pcs" : 1,"limit":0, "description" : null, "imgurl" : "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/114292.jpg", "featured" : false, "activation" : true, "qty" : 1, "sentToKitchen" : false, "status" : "proccessing", " addedToCart" :false},
  ]
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                